# Site settings
title : 虾米的四维空间
head_title : 华繁的博客
description: 华繁的思维空间
tagline: 业精于勤而荒于嬉，行成于思而毁于随。
url:
author:
    name: Huafan Li
    github: mioopoi
    email: huafan@seu.edu.cn
    twitter:
    facebook:
    weibo:
    zhihu:
    wiki: 
    stackoverflow: http://stackoverflow.com/
atom_path: /atom.xml
rss_path: /rss.xml
donate_url:

# Comment
comments:
  duoshuo:
    name:
    rcomments:
        num: 8
        avatar: 0
        time: 0
        title: 0
        admin: 1
        length: 20
  disqus:
    # In my architecture, duoshuo has higher priority then disqus,
    # because duoshuo is quicker then disqus in China.
    # if not only use in China, disqus is better.
    # disqus.name will be actived if duoshuo's name is null(Just delete it).
    name:
    rcomments:
        # Number of comments to show
        num: 8
        # Hide moderators' comments (1 for hidden, 0 for disabled)
        hide_mods: 0
        # Hide display images (1 for hidden, 0 for shown)
        hide_avatars: 1
        # Avatar size in pixels (32 by default)
        avatar_size: 32
        # Character-length of the excerpt (1000 by default)
        excerpt_length: 20
analytics:
    cnzz:
        uid: #1254858699

# Outputting
permalink: /:categories/:title
paginate_path: /page:num
paginate: 15
timezone: Asia/Shanghai

# Handling Reading
safe:         false
include:      []
exclude:      [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
keep_files:   []
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    redcarpet
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Backwards-compatibility
relative_permalinks: false

# Markdown Processors
redcarpet:
  extensions: [ "fenced_code_blocks",
                "hard_wrap",
                "autolink",
                "tables",
                "strikethrough",
     # DON'T USE"superscript", never use this with Mathjax,this will cause bug
                "with_toc_data",
                "highlight",
                "footnotes",
                "quote",
                "prettify",
                "no_intra_emphasis"]